version: '2.16.0'

x-srsue:
  &ue-settings
  image: srsran-image
  command: sh -c "cd srsRAN/build && ./srsue/src/srsue --rf.device_name=zmq --rf.device_args="tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6" --gw.netns=ue1"
  ipc: service:srsenb
  cap_add:
    - NET_ADMIN
    - SYS_NICE
  devices:
    - /dev/net/tun
  depends_on:
    - srsenb

services:
  srsepc:
    container_name: virtual-srsepc
    image: srsran-image
    command: sh -c "cd srsRAN/build && ./srsepc/src/srsepc"
    networks:
      zandaz:
        ipv4_address: 10.80.95.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
  srsenb:
    container_name: virtual-srsenb
    image: srsran-image
    command: sh -c "cd srsRAN/build && ./srsenb/src/srsenb --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6" "
    networks:
      zandaz:
        ipv4_address: 10.80.95.11
    ipc: shareable
    cap_add:
      - SYS_NICE
  srsue:
    << : *ue-settings
    container_name: virtual-srsue
  # srsue2:
  #   << : *ue-settings
  #   container_name: virtual-srsue2
  #   command: "srsue ue.conf.fauxrf --usim.imsi=001010123456780"

networks:
  zandaz:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24

